### PR TITLE
Become root before importing the RPM key

### PR DESCRIPTION
**Pull request by sbesson**
See also https://github.com/ome/ansible-role-cli-utils/pull/11

### CODE REVIEW

**Comment by dominikl** [comment]
👍 Thanks Seb. I guess that has to be released before I can test it in terms of IDR pilot, doesn't it?

**Comment by sbesson** [comment]
You should be able to pull the changes locally for testing.

If you are comfortable with it, you should be able to modify the local checkout of this role created when running `ansible-galaxy install`. Otherwise, I can update https://github.com/IDR/deployment/pull/413 to point at this branch. You will need to reinstall the roles locally.

**Comment by khaledk2** [comment]
Maybe it is worth to upgrade `min_ansible_version` to version 2.10 to be consistent with other roles 

https://github.com/sbesson/ansible-role-postgresql-client/blob/327a9216c37f56eb5e6cc328ddbe6cca86a2564a/meta/main.yml#L7

**Comment by sbesson** [comment]
> Maybe it is worth to upgrade min_ansible_version to version 2.10 to be consistent with other roles

Agreed but it looks like the value has already been updated in 8f0b3d3f0a6a1eb6413bff1e3c8e10ce3eaff23e

**Review by khaledk2 — APPROVED** [review]

**Pull request merged**
